sudo: required
services:
  - docker
before_install:
  - docker build -t nrjchnd2/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run nrjchnd2/react-test npm test -- --coverage
after_success:
  - docker build -t nrjchnd2/multi-client ./client
  - docker build -t nrjchnd2/multi-nginx ./nginx
  - docker build -t nrjchnd2/multi-server ./server
  - docker build -t nrjchnd2/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nrjchnd2/multi-worker
  - docker push nrjchnd2/multi-client
  - docker push nrjchnd2/multi-nginx
  - docker push nrjchnd2/multi-server
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker 
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-west-2-565965532131
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

  